### ISSUE TITLE
Filesystem layout

### ISSUE THREAD

**Issue by robin-nitrokey** [trussed-dev/trussed-auth#9]
Current implementation: PIN data is stored at `<client>/backend/auth/pin/<id>`.

Questions:
- backend identifier (see https://github.com/trussed-dev/trussed-auth/issues/8)
- do we need the `backend` dir?
- do we need the `pin` dir?

**Comment by daringer** [comment]
In general less (directory) depth is better for littlefs2 space & block utilization.

How about something like: `<client>/auth.backend/pin.<id>` ? 
Although `backend` is from my point of view not needed anyways...

**Comment by robin-nitrokey** [comment]
https://github.com/trussed-dev/trussed-auth/pull/13 changes `backend/auth` to `backend-auth`.

**Comment by daringer** [comment]
#13 partly fixes this ... 
changing `pin` storage from `pin/<id>` still has to be done.
